ARG PG_MAJOR=16

FROM postgres:${PG_MAJOR} AS binder-build
ARG PG_MAJOR
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      build-essential postgresql-server-dev-${PG_MAJOR} \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /src/agentsql_binder
COPY dbext/postgres/agentsql_binder/ ./
RUN make clean all install

FROM postgres:${PG_MAJOR}
ARG PG_MAJOR
COPY --from=binder-build /usr/lib/postgresql/16/lib/agentsql_binder.so /usr/lib/postgresql/16/lib/agentsql_binder.so
COPY --from=binder-build /usr/share/postgresql/16/extension/agentsql_binder.control /usr/share/postgresql/16/extension/agentsql_binder.control
COPY --from=binder-build /usr/share/postgresql/16/extension/agentsql_binder--0.4.sql /usr/share/postgresql/16/extension/agentsql_binder--0.4.sql

