-- Abort rather than silently dropping rows whose ownership cannot be represented.
CREATE TEMP TABLE b36_rollback_guard(value INTEGER);
CREATE TEMP TRIGGER b36_rollback_guard_trigger BEFORE INSERT ON b36_rollback_guard WHEN NEW.value > 0 BEGIN SELECT RAISE(ABORT,'cannot rollback business tenant ownership while non-default tenant rows exist'); END;
INSERT INTO b36_rollback_guard(value) SELECT COUNT(*) FROM (
  SELECT tenant_id FROM agents UNION ALL SELECT tenant_id FROM datasources UNION ALL SELECT tenant_id FROM policies UNION ALL SELECT tenant_id FROM rules UNION ALL SELECT tenant_id FROM mask_rules UNION ALL SELECT tenant_id FROM approvals UNION ALL SELECT tenant_id FROM notification_settings UNION ALL SELECT tenant_id FROM notification_channels UNION ALL SELECT tenant_id FROM redaction_key_versions UNION ALL SELECT tenant_id FROM management_audit_outbox UNION ALL SELECT tenant_id FROM chain_state UNION ALL SELECT tenant_id FROM chain_verification UNION ALL SELECT tenant_id FROM relation_policy_bindings UNION ALL SELECT tenant_id FROM policy_column_permission_staging UNION ALL SELECT tenant_id FROM policy_column_permissions UNION ALL SELECT tenant_id FROM b5_transactions UNION ALL SELECT tenant_id FROM b5_dml_grants UNION ALL SELECT tenant_id FROM b5_result_receipts UNION ALL SELECT tenant_id FROM b5_tx_events
) WHERE tenant_id <> 'tenant_default';
DROP TRIGGER b36_rollback_guard_trigger;
DROP TABLE b36_rollback_guard;

DROP INDEX idx_b5_tx_events_tenant; DROP INDEX idx_b5_result_receipts_tenant; DROP INDEX idx_b5_dml_grants_tenant; DROP INDEX idx_b5_transactions_tenant; DROP INDEX idx_b5_sessions_tenant; DROP INDEX idx_policy_column_permissions_tenant; DROP INDEX idx_policy_column_permission_staging_tenant; DROP INDEX idx_relation_policy_bindings_tenant; DROP INDEX idx_chain_verification_tenant; DROP INDEX idx_chain_state_tenant; DROP INDEX idx_management_audit_outbox_tenant; DROP INDEX idx_redaction_key_versions_tenant; DROP INDEX idx_notification_channels_tenant; DROP INDEX idx_notification_settings_tenant; DROP INDEX idx_approvals_tenant; DROP INDEX idx_mask_rules_tenant; DROP INDEX idx_rules_tenant; DROP INDEX idx_policies_tenant; DROP INDEX idx_datasources_tenant; DROP INDEX idx_agents_tenant;  DROP INDEX ux_redaction_key_versions_active; CREATE UNIQUE INDEX ux_redaction_key_versions_active ON redaction_key_versions(state) WHERE state='active'; DROP INDEX ux_mask_rules_scope_column; CREATE UNIQUE INDEX ux_mask_rules_scope_column ON mask_rules(COALESCE(NULLIF(TRIM(datasource_id),''),''),COALESCE(NULLIF(TRIM(schema_name),''),''),COALESCE(NULLIF(TRIM(table_name),''),''),LOWER(TRIM(column_name)));
ALTER TABLE notification_channels RENAME TO notification_channels_tenant; CREATE TABLE notification_channels (id TEXT PRIMARY KEY,position INTEGER NOT NULL CHECK(position>=0),enabled INTEGER NOT NULL DEFAULT 0,kind TEXT NOT NULL,decisions TEXT NOT NULL,include_sql INTEGER NOT NULL DEFAULT 0,allow_private_endpoints INTEGER NOT NULL DEFAULT 0,webhook_present INTEGER NOT NULL DEFAULT 0,webhook_template TEXT,webhook_url_enc TEXT,webhook_bearer_token_enc TEXT,webhook_headers_enc TEXT,webhook_secret_enc TEXT,syslog_present INTEGER NOT NULL DEFAULT 0,syslog_host TEXT,syslog_port INTEGER,syslog_transport TEXT,syslog_facility INTEGER,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(position)); INSERT INTO notification_channels(id,position,enabled,kind,decisions,include_sql,allow_private_endpoints,webhook_present,webhook_template,webhook_url_enc,webhook_bearer_token_enc,webhook_headers_enc,webhook_secret_enc,syslog_present,syslog_host,syslog_port,syslog_transport,syslog_facility,created_at,updated_at) SELECT id,position,enabled,kind,decisions,include_sql,allow_private_endpoints,webhook_present,webhook_template,webhook_url_enc,webhook_bearer_token_enc,webhook_headers_enc,webhook_secret_enc,syslog_present,syslog_host,syslog_port,syslog_transport,syslog_facility,created_at,updated_at FROM notification_channels_tenant WHERE tenant_id='tenant_default'; DROP TABLE notification_channels_tenant;
ALTER TABLE notification_settings RENAME TO notification_settings_tenant; CREATE TABLE notification_settings (id INTEGER PRIMARY KEY CHECK(id=1),enabled INTEGER NOT NULL DEFAULT 0,queue_size INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP); INSERT INTO notification_settings(id,enabled,queue_size,created_at,updated_at) SELECT id,enabled,queue_size,created_at,updated_at FROM notification_settings_tenant WHERE tenant_id='tenant_default'; DROP TABLE notification_settings_tenant;
ALTER TABLE chain_verification RENAME TO chain_verification_tenant; CREATE TABLE chain_verification (chain_id TEXT PRIMARY KEY,observed_instance_id TEXT,observed_head_hash TEXT,result TEXT,last_verified_head_seq INTEGER,last_verified_at TIMESTAMP,break_seq INTEGER,break_id INTEGER,break_reason TEXT); INSERT INTO chain_verification(chain_id,observed_instance_id,observed_head_hash,result,last_verified_head_seq,last_verified_at,break_seq,break_id,break_reason) SELECT chain_id,observed_instance_id,observed_head_hash,result,last_verified_head_seq,last_verified_at,break_seq,break_id,break_reason FROM chain_verification_tenant WHERE tenant_id='tenant_default'; DROP TABLE chain_verification_tenant;
ALTER TABLE chain_state RENAME TO chain_state_tenant; CREATE TABLE chain_state (chain_id TEXT PRIMARY KEY CHECK (chain_id IN ('management','traffic')),chain_instance_id TEXT,status TEXT NOT NULL CHECK (status IN ('DISABLED','BUILDING','ACTIVE','FAILED')),mode TEXT CHECK (mode IS NULL OR mode IN ('keyless','hmac')),head_seq INTEGER NOT NULL DEFAULT 0,head_id INTEGER,head_hash TEXT,genesis_at TIMESTAMP,protected_since_id INTEGER,build_owner TEXT,build_lease_until TIMESTAMP,build_epoch INTEGER NOT NULL DEFAULT 0,last_built_id INTEGER,last_built_seq INTEGER,last_built_hash TEXT,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP); INSERT INTO chain_state(chain_id,chain_instance_id,status,mode,head_seq,head_id,head_hash,genesis_at,protected_since_id,build_owner,build_lease_until,build_epoch,last_built_id,last_built_seq,last_built_hash,updated_at) SELECT chain_id,chain_instance_id,status,mode,head_seq,head_id,head_hash,genesis_at,protected_since_id,build_owner,build_lease_until,build_epoch,last_built_id,last_built_seq,last_built_hash,updated_at FROM chain_state_tenant WHERE tenant_id='tenant_default'; DROP TABLE chain_state_tenant;
ALTER TABLE b5_tx_events DROP COLUMN tenant_id; ALTER TABLE b5_result_receipts DROP COLUMN tenant_id; ALTER TABLE b5_dml_grants DROP COLUMN tenant_id; ALTER TABLE b5_transactions DROP COLUMN tenant_id; ALTER TABLE policy_column_permissions DROP COLUMN tenant_id; ALTER TABLE policy_column_permission_staging DROP COLUMN tenant_id; ALTER TABLE relation_policy_bindings DROP COLUMN tenant_id; ALTER TABLE management_audit_outbox DROP COLUMN tenant_id; ALTER TABLE redaction_key_versions DROP COLUMN tenant_id; ALTER TABLE approvals DROP COLUMN tenant_id; ALTER TABLE mask_rules DROP COLUMN tenant_id; ALTER TABLE rules DROP COLUMN tenant_id; ALTER TABLE policies DROP COLUMN tenant_id; ALTER TABLE datasources DROP COLUMN tenant_id; ALTER TABLE agents DROP COLUMN tenant_id;
